/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc_sort_alg.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

ascii_chars *
bubble_sort_1(ascii_chars *argp, CLIENT *clnt)
{
	static ascii_chars clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, bubble_sort,
		(xdrproc_t) xdr_ascii_chars, (caddr_t) argp,
		(xdrproc_t) xdr_ascii_chars, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ascii_chars *
merge_sort_1(ascii_chars *argp, CLIENT *clnt)
{
	static ascii_chars clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, merge_sort,
		(xdrproc_t) xdr_ascii_chars, (caddr_t) argp,
		(xdrproc_t) xdr_ascii_chars, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
