/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_sort_alg.h"
#include<stdlib.h>


void
sort_prg_1(char *host,int n,int buf[n])
{
	CLIENT *clnt;
	ascii_chars  *result_1;
	ascii_chars  bubble_sort_1_arg;
	ascii_chars  *result_2;
	ascii_chars  merge_sort_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SORT_PRG, SORT_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	int c;

	bubble_sort_1_arg.n = n;
	merge_sort_1_arg.n = n;

	for(c=0;c<n;c++){
		bubble_sort_1_arg.buf[c] = buf[c];
		merge_sort_1_arg.buf[c] = buf[c];
	}

	result_1 = bubble_sort_1(&bubble_sort_1_arg, clnt);
	if (result_1 == (ascii_chars *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("Bubble Sorted Characters are ");
		for(c=0;c<result_1->n;c++){
			printf("%c ",(char)result_1->buf[c]);
		}
		printf("\n");
	}
	result_2 = merge_sort_1(&merge_sort_1_arg, clnt);
	if (result_2 == (ascii_chars *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("Merge Sorted Characters are ");
		for(c=0;c<result_2->n;c++){
			printf("%c ",(char)result_2->buf[c]);
		}
		printf("\n");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int n;
retry:printf("Enter No.of Items in the range(15,40):-");
	scanf("%d",&n);
	if(n<15 || n>40){
		printf("Incorrect output.\n");
		goto retry;
	}
	FILE *filep;
	filep = fopen("input.txt","w");

	int c,d;

	int buf[40];
	srand(time(0));
	for(c=0;c<3;c++){
		for(d=0;d<n;d++){
			buf[d] = rand()%(126 - 33 + 1);
			fprintf(filep,"%d ",buf[d]);
		}
		fprintf(filep,"\n");
		sort_prg_1 (host,n,buf);
	}
	exit (0);
}
