/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_SORT_ALG_H_RPCGEN
#define _RPC_SORT_ALG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct ascii_chars {
	int buf[40];
	int n;
};
typedef struct ascii_chars ascii_chars;

#define SORT_PRG 0x23451111
#define SORT_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define bubble_sort 1
extern  ascii_chars * bubble_sort_1(ascii_chars *, CLIENT *);
extern  ascii_chars * bubble_sort_1_svc(ascii_chars *, struct svc_req *);
#define merge_sort 2
extern  ascii_chars * merge_sort_1(ascii_chars *, CLIENT *);
extern  ascii_chars * merge_sort_1_svc(ascii_chars *, struct svc_req *);
extern int sort_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define bubble_sort 1
extern  ascii_chars * bubble_sort_1();
extern  ascii_chars * bubble_sort_1_svc();
#define merge_sort 2
extern  ascii_chars * merge_sort_1();
extern  ascii_chars * merge_sort_1_svc();
extern int sort_prg_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ascii_chars (XDR *, ascii_chars*);

#else /* K&R C */
extern bool_t xdr_ascii_chars ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_SORT_ALG_H_RPCGEN */
